name: nzx-api
services:
- name: api
  github:
    repo: your-repo
    branch: main
    deploy_on_push: true
  build_command: pip install -r requirements.txt
  run_command: uvicorn main:app --host 0.0.0.0 --port $PORT 